version: '3'
services:
  gekko:
    restart: always
    build: ./
    volumes:
      - ./:/usr/src/app/
    links:
      - redis
    environment:
     - HOST
     - PORT
    ports:
      - "${PORT}:${PORT}"
    # to uncomment the first time
    # command: npm install

  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data
